server:
  port: 8080
  servlet:
    context-path: /video
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.3.187:3306/video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 118.190.101.57
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 100

mybatis:
  type-aliases-package: top.yinjinbiao.video.domain
  mapper-locations: classpath:mapper/*.xml
  
# 阿里云对象存储地址
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketName: top-yinjinbiao-video
  bucket-endpoint: https://top-yinjinbiao-video.oss-cn-beijing.aliyuncs.com/

